name: hackru
description: The Official HackRU Flutter App
version: 1.2.0
publish_to: none
homepage: http://hackru.org/
repository: https://github.com/HackRU/OneAppFlutter

environment:
  # sdk: ">=2.13.0 <3.0.0"
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # App Dependencies from (https://pub.dev/)
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  # firebase_messaging: ^11.2.11
  # flare_flutter: ^3.0.2
  flutter_launcher_icons: ^0.10.0
  flutter_linkify: ^5.0.2
  # flutter_local_notifications: ^9.4.0
  font_awesome_flutter: ^9.2.0
  hidden_drawer_menu: ^3.0.1
  jsqr: ^0.1.4
  qr_flutter: ^4.0.0
  # qr_code_scanner: ^0.7.0
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.4.0
  meta: ^1.7.0
  # mobile_scanner: ^1.0.0
  mobile_scanner:
    path: depend/mobile_scanner-more_fixes
  # path_provider: ^2.0.9
  provider: ^6.0.2
  # rive: ^0.8.4
  rubber: ^1.0.1
  # rxdart: ^0.27.3
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  url_strategy: ^0.2.0
  webview_flutter: ^3.0.1

dev_dependencies:
  test: ^1.20.2
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/hackru-logos/hackru_red.png"

flutter:
  # generate: true
  uses-material-design: true
  assets:
  - assets/
  - assets/assets-png/
  - assets/assets-svg/
  - assets/hackru-logos/
  - assets/map/
  - assets/flare/

  fonts:
  - family: TitilliumWeb
    fonts:
    - asset: assets/fonts/TitilliumWeb-Regular.ttf
