name: HackRU
description: The Official HackRU Flutter App
version: 1.0.0+1
author: HackRU RnD Flutter Team [Dhruvil Patel & Sean Lane]
homepage: https://github.com/HackRU/OneAppFlutter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.2.0
  groovin_material_icons: ^1.1.6
  hidden_drawer_menu: ^0.5.0
  pinch_zoom_image: ^0.2.5
  qrcode_reader: ^0.4.4
  qr_mobile_vision: ^0.1.0
  qr_flutter: ^1.1.6
  http: ^0.12.0+1
  flutter_linkify: ^1.0.3
  url_launcher: ^5.0.0
  flutter_webview_plugin: ^0.3.0+2
  flutter_bloc: ^0.5.3
  bloc: ^0.8.2
  equatable: ^0.1.10
  meta: ^1.1.6
  flip_panel: ^0.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - assets/images/hackru_black_logo.png
  - assets/images/hackru_circle_logo.png
  - assets/images/hackru_green_logo.png
  - assets/images/hackru_pink_logo.png
  - assets/images/hackru_white_logo.png
  - assets/images/drawer_bg.png
  - assets/images/cover_image.png
  - assets/images/map/event_map.png
  - assets/images/map/foodArea.png
  - assets/images/map/hackingArea.png
  - assets/images/map/registration.png
  - assets/images/map/stageArea.png

  fonts:
  - family: OpenSans
    fonts:
    - asset: assets/fonts/OpenSans-Regular.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
